# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"

issues:
  exclude-rules:
    # Exclude gosimple bool check
    - linters:
        - gosimple
      text: "S(1002|1008|1021)"
    # Exclude failing staticchecks for now
    - linters:
        - staticcheck
      text: "SA(1006|1019|4006|4010|4017|5007|6005|9004):"
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - errcheck
      path: ".*_test.go"

  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-files:
    - ".*\\.hcl2spec\\.go$"

linters:
  default: none
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused

run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions: fmt:.*,io/ioutil:^Read.*,io:Close
