name: Pull Request Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: check fmt
        run: |
          go fmt ./...
          echo "==> Checking that code complies with go fmt requirements..."
          git diff --exit-code; if [ $$? -eq 1 ]; then \
                echo "Found files that are not fmt'ed."; \
                echo "You can use the command: \`make fmt\` to reformat code."; \
                exit 1; \
          fi

      - name: check lint
        run: |
          echo "==> Updating linter dependencies..."
          curl -sSfL -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
          echo "==> Running linter on newly added Go source files..."
          GO111MODULE=on golangci-lint run --new-from-rev=$(shell git merge-base origin/main HEAD) ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: test
        run: go test -count 1 ./... -timeout=3m

